[package]
name = "mini-redis-rs"
version = "0.1.0"
authors = ["yinkam <5328632+yinkam@users.noreply.github.com>"]
edition = "2021"

[dependencies]
mio = { version = "1.1.1", features = ["net", "os-poll"] }
num-bigint = "0.4.6"
