[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"

[dependencies]
mio = { version = "1.1.1", features = ["net", "os-poll"] }
num-bigint = "0.4.6"
